/**
 * Utilities Index
 * 
 * Centralized exports for all utility modules.
 * Provides clean, organized access to all utility functions.
 */

// ===== API RESPONSES =====
export {
  createSuccessResponse,
  createPaginatedResponse,
  createErrorResponse,
  respondWithData,
  respondWithValidationErrors,
  respondWithNotFound,
  respondWithUnauthorized,
  respondWithForbidden,
  respondWithRateLimited,
  respondWithServerError,
  createPaginationMeta,
  addResponseMeta,
  createResponseWithMeta,
  type ApiResponse,
  type PaginationMeta,
  type ErrorResponse
} from './api-responses';

// ===== REQUEST VALIDATION =====
export {
  emailSchema,
  passwordSchema,
  phoneSchema,
  mongoIdSchema,
  uuidSchema,
  urlSchema,
  dateRangeSchema,
  paginationSchema,
  sortSchema,
  sanitizeEmail,
  sanitizeString,
  sanitizePhone,
  sanitizeFileName,
  sanitizeUrl,
  validateWithSchema,
  parseAndValidate,
  validateEmail,
  validatePassword,
  validatePhone,
  validateMongoId,
  validateUUID,
  validateUrl,
  escapeHtml,
  normalizeUnicode,
  validateFilePath,
  sanitizeSqlInput,
  createUserSchema,
  updateUserSchema,
  loginSchema,
  idParamSchema,
  searchSchema
} from './request-validation';

// ===== QUERY PARAMETERS =====
export {
  parsePagination,
  parsePaginationWithValidation,
  parseSortParams,
  parseSortParamsWithValidation,
  parseFilterParams,
  parseFilterParamsWithValidation,
  parseSearchParams,
  parseSearchParamsWithValidation,
  parseDateRange,
  parseDateRangeWithValidation,
  parseIncludeFields,
  parseIncludeFieldsWithValidation,
  parseQueryParams,
  buildMongoQuery,
  buildMongoSort,
  buildMongoTextSearch,
  buildDateRangeQuery,
  combineQueries,
  cleanQuery,
  validateQueryParams,
  type PaginationParams,
  type SortParams,
  type FilterParams,
  type SearchParams,
  type DateRangeParams,
  type IncludeParams
} from './query-params';

// ===== ERROR HANDLING =====
export {
  AppError,
  ValidationError,
  NotFoundError,
  AuthError,
  AuthorizationError,
  RateLimitError,
  DatabaseError,
  handleDatabaseError,
  handleValidationError,
  handleAuthError,
  handleNotFoundError,
  handleRateLimitError,
  handleGenericError,
  formatErrorForClient,
  formatZodError,
  formatMongooseError,
  formatMongooseErrors,
  logErrorWithContext,
  logErrorForMonitoring,
  logInfo,
  logDebug,
  logWarn,
  isOperationalError,
  shouldRetryError,
  withErrorHandling,
  createErrorHandler,
  sanitizeErrorForProduction
} from './error-handling';

// ===== DATA TRANSFORMERS =====
export {
  transformUser,
  transformUserPublic,
  transformSession,
  transformPatient,
  transformTransfer,
  transformAuditLog,
  paginateResults,
  sanitizeForPublicAPI,
  objectIdToString,
  stringToObjectId,
  isValidObjectId,
  dateToISOString,
  convertDatesToISO,
  transformArray,
  transformArrayWithPagination,
  type TransformOptions,
  type PaginatedResult
} from './transformers';

// ===== FILE UPLOADS =====
export {
  validateFileType,
  validateFileSize,
  validateImageDimensions,
  validateFile,
  generateUniqueFileName,
  getFileExtension,
  getMimeType,
  calculateFileChecksum,
  getFileInfo,
  getImageDimensions,
  isImageFile,
  isDocumentFile,
  formatFileSize,
  getMaxSizeForFileType,
  isSafeFileName,
  generateUploadPath,
  validateUploadPath,
  createUploadMetadata,
  ALLOWED_IMAGE_TYPES,
  ALLOWED_DOCUMENT_TYPES,
  MAX_FILE_SIZES,
  DANGEROUS_EXTENSIONS,
  MIME_TYPE_MAP,
  type FileValidationResult,
  type FileInfo,
  type ImageDimensions
} from './file-uploads';

// ===== DATE/TIME =====
export {
  formatDate,
  formatDateForDisplay,
  formatDateTimeForDisplay,
  formatTime,
  formatDateISO,
  formatDateForAPI,
  parseDate,
  parseDateWithFallback,
  parseDateFlexible,
  isValidDate,
  isValidDateRange,
  isWithinRange,
  addDaysToDate,
  addHoursToDate,
  addMinutesToDate,
  addMonthsToDate,
  addYearsToDate,
  subtractDaysFromDate,
  subtractHoursFromDate,
  subtractMinutesFromDate,
  subtractMonthsFromDate,
  subtractYearsFromDate,
  calculateDateDiff,
  calculateDuration,
  getDateRangeForPeriod,
  getTimePeriods,
  formatDuration,
  formatDurationShort,
  setTimeOnDate,
  getTimeComponents,
  isToday,
  isYesterday,
  isFuture,
  isPast,
  getTimezoneOffset,
  convertToTimezone,
  getCurrentTimestamp,
  getCurrentDateISO,
  getCurrentDate,
  createDateFromTimestamp,
  getDateParts,
  compareDates,
  type DateRange,
  type TimePeriod,
  type Duration
} from './date-time';

// ===== STRING HELPERS =====
export {
  slugify,
  truncate,
  capitalize,
  titleCase,
  sentenceCase,
  camelCase,
  pascalCase,
  kebabCase,
  snakeCase,
  generateRandomString,
  generateRandomAlphanumeric,
  generateRandomNumeric,
  generateUUID,
  maskEmail,
  maskPhone,
  maskCreditCard,
  maskSensitiveData,
  removeAccents,
  unescapeHtml,
  stripHtml,
  normalizeWhitespace,
  removeExtraSpaces,
  removeLineBreaks,
  cleanText,
  isValidEmail,
  isValidPhone,
  isValidUrl,
  isAlpha,
  isNumeric,
  isAlphanumeric,
  formatPhone,
  formatCurrency,
  formatNumber,
  formatPercentage,
  highlightSearchTerms,
  escapeRegex,
  findAllOccurrences,
  reverse,
  removeDuplicates,
  countWords,
  countCharacters,
  countLines,
  padString,
  repeatString,
  chunkString,
  joinStrings,
  startsWith,
  endsWith,
  contains,
  type TruncateOptions,
  type MaskOptions
} from './string-helpers';

// ===== DATA HELPERS =====
export {
  groupBy,
  sortBy,
  filterBy,
  unique,
  uniqueBy,
  chunk,
  flatten,
  compact,
  intersection,
  difference,
  union,
  pickFields,
  omitFields,
  deepMerge,
  deepClone,
  flattenObject,
  unflattenObject,
  isPlainObject,
  isArray,
  isFunction,
  isString,
  isNumber,
  isBoolean,
  first,
  last,
  random,
  shuffle,
  sample,
  tail,
  head,
  take,
  drop,
  getNestedProperty,
  setNestedProperty,
  removeNestedProperty,
  hasNestedProperty,
  mapValues,
  filterObject,
  invertObject,
  getKeys,
  getValues,
  getEntries,
  fromPairs,
  toPairs,
  size,
  type GroupByResult,
  type SortOptions,
  type FilterOptions,
  type ChunkOptions
} from './data-helpers';

// ===== ASYNC HELPERS =====
export {
  retry,
  withRetry,
  retryWithCondition,
  timeout,
  withTimeout,
  createTimeout,
  batchProcess,
  sequential,
  parallel,
  createConcurrencyLimiter,
  createSemaphore,
  debounce,
  debounceAsync,
  throttle,
  throttleAsync,
  sleep,
  resolved,
  rejected,
  never,
  waitFor,
  waitForEvent,
  firstSuccess,
  allSettled,
  firstSettled,
  createAsyncIterator,
  processAsyncIterator,
  type RetryOptions,
  type TimeoutOptions,
  type BatchProcessOptions,
  type ParallelOptions
} from './async-helpers';
