/**
 * Auth Error Types
 * 
 * Authentication error codes and types.
 */

export enum AuthErrorCode {
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  ACCOUNT_NOT_APPROVED = 'ACCOUNT_NOT_APPROVED',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  SESSION_REVOKED = 'SESSION_REVOKED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  RATE_LIMITED = 'RATE_LIMITED',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  SUSPICIOUS_ACTIVITY = 'SUSPICIOUS_ACTIVITY',
  IP_MISMATCH = 'IP_MISMATCH',
  DEVICE_NOT_TRUSTED = 'DEVICE_NOT_TRUSTED',
  TOO_MANY_SESSIONS = 'TOO_MANY_SESSIONS',
  AUTHENTICATION_REQUIRED = 'AUTHENTICATION_REQUIRED',
  INTERNAL_ERROR = 'INTERNAL_ERROR'
}

export interface AuthError {
  code: string;
  message: string;
  status: number;
  details?: any;
}

